name: insurance-ml
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - notebook
  - ipykernel
  - pip
  - pip:
    - xgboost
    - lightgbm
    - shap
    - pandas-profiling
